CREATE TABLE subjects (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  description VARCHAR(255) NULL,
  gradeLevel VARCHAR(50) NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE class_schedules
  DROP COLUMN subject,
  ADD COLUMN subjectId INT UNSIGNED NOT NULL AFTER teacherId,
  ADD CONSTRAINT fk_cs_subject FOREIGN KEY (subjectId) REFERENCES subjects(id) ON DELETE RESTRICT;

ALTER TABLE bookings
  ADD COLUMN subjectId INT UNSIGNED NULL AFTER purpose,
  ADD CONSTRAINT fk_bookings_subject FOREIGN KEY (subjectId) REFERENCES subjects(id) ON DELETE SET NULL;
